name: Firebase Hosting Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner (Ubuntu in this case)

    steps:
      # Checkout your code from GitHub to the runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js for the React app (or any other JavaScript framework you're using)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want to use

      # Install dependencies listed in package.json (assumes you're using npm)
      - run: npm install  # Runs npm install to install the project dependencies

      # Build the app (assuming you're using React or a similar framework)
      - run: npm run build  # Runs npm run build (or use the equivalent build command for your app)

      # Deploy the built app to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebase_project_id: ${{ arabiantandoor-1f874 }}  # Replace with your Firebase project ID secret
          firebase_token: ${{ 1//0gltkIloLaM2MCgYIARAAGBASNwF-L9Ir944W9njhgAGMsuY7x9QRtLtk26O5teJDxQ4GD_r7WEE0PsbGncJvezBLP8-N1PBd4T0 }}  # Firebase Authentication Token
          firebase_service_account_key: ${{ -----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeQ4676X5VX8H3\nBrfICfc+62XG+Xnemt7+QoY09aBkKhRfzTzxK43j/79KRbL/xsa+4L4xLnPiDrwx\nHR7FCrGK8ERbyia/UFuAhKWaeKYh3FTpTWbLpQ7fAFlAaifXHNgxOUfCXrmelai/\nALreCd3L+y4W7NqjVHHcByNcLYzxC0JiuF6ZTzyvP5zfLn7mbRCMZfrbxLNtUAKJ\nekJ7/YMdey2kIYcIaTMdsP6Vv8wdYfCVuB/Ct8XVR/Z92VzGemaBlGynmN8B2epr\n64t8X3ijFSLLrb3fSIqOzixmLqh5K5UQCgGQGrlC+KGjVZ1KqHEZfNQE0ZyU0fim\neTpV4giXAgMBAAECggEAAbPj2QkIPMmqespkU1QLCjM8+7eIfQ/Ibl4Y68+HjRVb\ny2wWrBN6saygaw4BwTeDQ44FUkWaLrj6SwoG8+fVAeNqX9LRKJWv5FoYQuqfsj+I\nn7KRc+nPneIURW3DOxOkI6Rlk5IHBls4rgMV1M359PIGiwLFJYuGAagI0DHnfYF1\nVLwIpWPHsaffXhXAK2/tyayBh1Irzn/CZPW5DKtrevBxZBl2Yj4QiHKw+3ht6yJ8\nu9InVDjHBHpG3F+3V58EhYuSRl/w/scYj931amkNqk7zEim1U+Q7qti+FBy4wnfm\niBLABw/xvQjFfrPB07y/RMgY4c2Ut5kkvH9nSJ8T0QKBgQD193ZtE3BCMTD7WlzQ\nE1gQkOrfiK+D5nvf+CKlRfzYbJdswlqpMO23f1RV+EZnsMkk8TwIYneio8bK0nwD\nutsSj94N0rRyKXdV2OvrvGdEDUBS/Pw9V7gHNma2wPn5idf/4WpiT51mCoOMZz/k\nOLUti/59i4rCp0YSMwNm1cb5KQKBgQDnVJN0FNiEXPwVKvyBMpfW8WctaMWLzo5V\nQESu23sdzixSIw8OV7+nctiVwZ3/LSHgNhqQXGMUIFFeBxeqjCTJ++xFi0QwEgRv\nfYb2onxw5iRfbAkDxyqEmCwzAzB1o51WoLKWQmS91KWVZesKlQB1UDV5OlKsdJdW\nXLaikTprvwKBgQCXgUZBCagsHYC+Unq48DFeguUpq1fxNxc2bfFpPCLybHEZXN3b\nOXgzfwrDqZo0ZICBcNY5k+19EMRyShR5d69ZT6THfvIHH+ORzXwESJiTIlZsx8fX\nQSDp0GiUSWmwe2fBBWgyBjg9klxVL4P7X7K5y3GGg12FaOOQcju2LBfTgQKBgHfU\nG72Zvr5x3DKq3bmfF4BD9ApVp17QVHJcpDdfgdrinZq+hmILmj+HAiIw9ULlghK+\nc+wrrzcRtpRaYCv8BGKMmMs9ZMjxzFJkV7ESYhupW1YChHjshl3A5cRW9pc5dZsW\nCuxC4CRlLpDBBouou2AJeGmfiIvEqVAXHpP/Xp/JAoGBALnsnlCaL7oPDXWQEUcU\nbftNvn7S3Vl24r6S3vjg+7hjnXigWXFxr9tlrDKrUY+x301w9puurUkVBuWjcmxp\nwXPSLffZRKjh6wXyAFM/d2AztN2DhvZSd8n+XXO/dufk3tUdJBtHzfDT34+Y4WyD\nJVAK8MMvqhmnGZxRpHkuuLa8\n-----END PRIVATE KEY----- }}  # Service Account Key
